### ISSUE TITLE
Cannot sync transactions with backend l2

### ISSUE THREAD

**Issue by Jakelee24** [optimisticben/op-replica#18]
I'm trying to run a mainnet, but I got stuck when l1-blocknumber=12821447

**l2_geth:**
`ERROR[07-23|02:44:16.458] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: cannot fetch transaction 34516: cannot fetch transaction: 
json: cannot unmarshal hex number > 64 bits into Go struct field transaction.transaction.value of type hexutil.Uint64"
INFO [07-23|02:44:16.458] Set L2 Gas Price                         gasprice=1000000
ERROR[07-23|02:44:16.459] Cannot update L1 gas price               msg="cannot fetch L1 gas price: Cannot parse response as big number"
INFO [07-23|02:44:16.460] Syncing transaction range                start=34516 end=96098 backend=l2
`

**dtl:**
`{"level":50,"time":1627008256458,"extra":{"method":"GET","url":"/eth/gasprice","elapsed":0,"msg":"TypeError: Cannot read property 'getGasPrice' of null","stack":"TypeError: Cannot read property 'getGasPrice' of null\n    at /opt/optimism/packages/data-transport-layer/dist/sr
c/services/server/service.js:205:61\n    at /opt/optimism/packages/data-transport-layer/dist/src/services/server/service.js:128:36\n    at Layer.handle [as handle_request] (/opt/optimism/node_modules/express/lib/router/layer.js:95:5)\n    at next (/opt/optimism/node_modules/
express/lib/router/route.js:137:13)\n    at Route.dispatch (/opt/optimism/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/opt/optimism/node_modules/express/lib/router/layer.js:95:5)\n    at /opt/optimism/node_modules/express/lib/rou
ter/index.js:281:22\n    at Function.process_params (/opt/optimism/node_modules/express/lib/router/index.js:335:12)\n    at next (/opt/optimism/node_modules/express/lib/router/index.js:275:10)\n    at middleware (/opt/optimism/node_modules/express-prom-bundle/src/index.js:20
4:5)\n    at Layer.handle [as handle_request] (/opt/optimism/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/optimism/node_modules/express/lib/router/index.js:317:13)\n    at /opt/optimism/node_modules/express/lib/router/index.js:284:7\n    at Functi
on.process_params (/opt/optimism/node_modules/express/lib/router/index.js:335:12)\n    at next (/opt/optimism/node_modules/express/lib/router/index.js:275:10)\n    at cors (/opt/optimism/node_modules/cors/lib/index.js:188:7)"},"msg":"Failed HTTP Request"}
{"level":30,"time":1627008256459,"method":"GET","url":"/transaction/latest?backend=l2","elapsed":0,"msg":"Served HTTP Request"}
{"level":30,"time":1627008256460,"method":"GET","url":"/transaction/index/34516?backend=l2","elapsed":0,"msg":"Served HTTP Request"}`

**Comment by optimisticben** [comment]
Please update to the newest l2geth and data-transport-layer images and open a new issue if you're still having a problem.
