### ISSUE TITLE
Wrong hash

### ISSUE THREAD

**Issue by pleasecoding** [optimisticben/op-replica#22]
Using https://kovan.optimism.io/ as rpc end point, call eth_getBlockByNumber:

{
	"jsonrpc":"2.0",
	"method":"eth_getBlockByNumber",
	"params":[
		"0x2", 
		true
	],
	"id":1
}

will get:
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "difficulty": "0x2",
        "extraData": "0xd68301090a846765746886676f312e3136856c696e75780000000000000000001cc85645877d41a934a0a3ed0ec6f3369f41b394b7ef61fa32e3ddca6ed171437f0139c3975d4633fbad271b0609eb03fc449d07254ff86c47c2b0fd7410647101",
        "gasLimit": "0xa7d8c0",
        "gasUsed": "0x1dda15",
        "hash": "0x49f0dd5f976f3ffc2bd0a2dd5aa01efc2575ac59b266edd4d162e7853abcdfc9",
        "logsBloom": "0x00080000000000000000000000000000000000000000000000040000008000000000000004040000000000100000000100000000000200000000000000000000100000000000000000020008002000000000000001000000000000400100000000000000000000000000000000000000400000000400000000000010100020000000000000800000000000000000000000000480022020000000000000000000000000001000000000000000000000000000000400040000000000000000000000000002000000000000000000000008000000000000000000000000000000000000000010000008000000000000000000010000000000000000000001000000",
        "miner": "0x0000000000000000000000000000000000000000",
        "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "nonce": "0x0000000000000000",
        "number": "0x2",
        "parentHash": "0x8cbaab164a302ab39dbc008cbfd5433cc9fa19d9971017c78333b07ef4fa4a79",
        "receiptsRoot": "0xcd88793459542f6e32483b1af42044171bddb96ea0883ee21aa22d4e24c6d0a3",
        "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
        "size": "0x30d",
        "stateRoot": "0x68e4d6c03f090cd17094daf9e72a72692b6aa2e631a8cad9efc4a1f6487fbb9b",
        "timestamp": "0x60ca4094",
        "totalDifficulty": "0x5",
        "transactions": [
            {
                "blockHash": "0x49f0dd5f976f3ffc2bd0a2dd5aa01efc2575ac59b266edd4d162e7853abcdfc9",
                "blockNumber": "0x2",
                "from": "0xb7234440fc334b120e0a476a7b3e6758153f54a8",
                "gas": "0x2dc6c0",
                "gasPrice": "0x0",
                "hash": "0x71dc4e5e0e1334a7ace0a8973c6b66fc8c10de32a4d7f4610cdaffe50781fcfe",
                "input": "0x202ee0ed000000000000000000000000000000000000000000000000000000000000e41f0000000000000000000000000000000000000000000000000000038469a372e9",
                "nonce": "0x5ff56",
                "to": "0xf56f6c47e39293e1a763e56175bc8386fdfe6162",
                "transactionIndex": "0x0",
                "value": "0x0",
                "v": "0xad",
                "r": "0xe1aaff698632d0b7c3bc09b44edb0c05c891e8dde721feb93cde501b1a8ed7c3",
                "s": "0x5631589df0229912a518e5943c1afa84c27c7f888561905e7045c3a743f289e5",
                "queueOrigin": "sequencer",
                "txType": "",
                "l1TxOrigin": null,
                "l1BlockNumber": "0x18569a2",
                "l1Timestamp": "0x60ca4094",
                "index": "0x1",
                "queueIndex": null,
                "rawTransaction": "0xf8a98305ff5680832dc6c094f56f6c47e39293e1a763e56175bc8386fdfe616280b844202ee0ed000000000000000000000000000000000000000000000000000000000000e41f0000000000000000000000000000000000000000000000000000038469a372e981ada0e1aaff698632d0b7c3bc09b44edb0c05c891e8dde721feb93cde501b1a8ed7c3a05631589df0229912a518e5943c1afa84c27c7f888561905e7045c3a743f289e5"
            }
        ],
        "transactionsRoot": "0x2abfd60b4f00f3fd3195229329ba8862436ece060a849edeeddf87046b2a5f75",
        "uncles": []
    }
}

However, use this repo, it will return:
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "difficulty": "0x3ff001000",
        "extraData": "0x476574682f76312e302e302d30636463373634372f6c696e75782f676f312e34",
        "gasLimit": "0x1388",
        "gasUsed": "0x0",
        "hash": "0xb495a1d7e6663152ae92708da4843337b958146015a2802f4193a410044698c9",
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "miner": "0xdd2f1e6e498202e86d8f5442af596580a4f03c2c",
        "mixHash": "0x2f0790c5aa31ab94195e1f6443d645af5b75c46c04fbf9911711198a0ce8fdda",
        "nonce": "0xb853fa261a86aa9e",
        "number": "0x2",
        "parentHash": "0x88e96d4537bea4d9c05d12549907b32561d3bf31f45aae734cdc119f13406cb6",
        "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
        "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
        "size": "0x220",
        "stateRoot": "0x4943d941637411107494da9ec8bc04359d731bfd08b72b4d0edcbd4cd2ecb341",
        "timestamp": "0x55ba4241",
        "totalDifficulty": "0xbfe801000",
        "transactions": [],
        "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
        "uncles": []
    }
}

The results are quite different.

**Comment by tynes** [comment]
There is currently a problem with nondeterministic block hashes between nodes. This has been patched here: https://github.com/ethereum-optimism/optimism/commit/11d461824b9d63178ab7277afe0309879306342b and a longer term solution will be put out eventually

**Comment by PetruchoEbovski** [comment]
@optimisticben 
Hey, 
Regarding to your commits L1 is not needed anymore, env.example is ready covan config. I have tried to deploy op-replica and faced following issue. There are steps to reproduce issue:
1. Git clone op-replica repository;
2. cp env.example .env
3. Docker-compose up -d

**Log healthcheck replica.** 
```
{"level":30,"time":1635780406552,"msg":"Listening on port 3000"}
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.4.4)
    at Logger.makeError (/opt/optimism/node_modules/@ethersproject/logger/lib/index.js:187:21)
    at Logger.throwError (/opt/optimism/node_modules/@ethersproject/logger/lib/index.js:196:20)
    at StaticJsonRpcProvider.<anonymous> (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:491:54)
    at step (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}
```

**Data transport layer log.** 
```
{"level":30,"time":1635780539039,"fromBlock":15186,"toBlock":15187,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimistic Ethereum)"}
{"level":50,"time":1635780543918,"extra":{"method":"GET","url":"/eth/context/latest","elapsed":0,"msg":"TypeError: Cannot read property 'getBlockNumber' of null","stack":"TypeError: Cannot read property 'getBlockNumber' of null\n    at /opt/optimism/packages/data-transport-layer/dist/src/services/server/service.js:258:56\n    at /opt/optimism/packages/data-transport-layer/dist/src/services/server/service.js:163:36\n    at Layer.handle [as handle_request] (/opt/optimism/node_modules/express/lib/router/layer.js:95:5)\n    at next (/opt/optimism/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/opt/optimism/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/opt/optimism/node_modules/express/lib/router/layer.js:95:5)\n    at /opt/optimism/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/opt/optimism/node_modules/express/lib/router/index.js:335:12)\n    at next (/opt/optimism/node_modules/express/lib/router/index.js:275:10)\n    at middleware (/opt/optimism/node_modules/express-prom-bundle/src/index.js:204:5)\n    at Layer.handle [as handle_request] (/opt/optimism/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/optimism/node_modules/express/lib/router/index.js:317:13)\n    at /opt/optimism/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/opt/optimism/node_modules/express/lib/router/index.js:335:12)\n    at next (/opt/optimism/node_modules/express/lib/router/index.js:275:10)\n    at cors (/opt/optimism/node_modules/cors/lib/index.js:188:7)"},"msg":"Failed HTTP Request"}
```

**Comment by optimisticben** [comment]
> Log healthcheck replica.

This will fail on the first startup because there is no "wait" configured in docker-compose at the moment.

A subsequent `docker-compose up` once l2geth-deplica start should get it checking.

I opened an issue https://github.com/ethereum-optimism/optimism/issues/1661

>Data transport layer log.


`DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT` does indeed seem to still be required even with `DATA_TRANSPORT_LAYER__L1_GAS_PRICE_BACKEND=l2`, I may have misunderstood the changes 😬

**Comment by PetruchoEbovski** [comment]
@optimisticben thanks! It helped!
