### ISSUE TITLE
l2geth memory usage over 64G

### ISSUE THREAD

**Issue by Allen-yan** [optimisticben/op-replica#23]
The .env context
`
L1_RPC_ENDPOINT=*
DTL_IMAGE_TAG=0.4.4
DTL_PORT=7879
ETH_NETWORK=kovan
ETH_NETWORK_RPC_PROVIDER=https://kovan.optimism.io
ETH_REPLICA_RPC_PROVIDER=http://localhost:9991
L2GETH_HTTP_PORT=9991
L2GETH_IMAGE_TAG=0.4.7
`

l2geth have some many logs like this:
`
INFO [08-10|09:43:15.832] New block                                index=10528 l1-timestamp=1623949464 l1-blocknumber=25541022 tx-hash=0xe81a557b253532a37ff338dbdd9c9d77bf8408fdc08ef61c3acab604a1333a7d queue-orign=sequencer gas=760728  fees=1.141092e-05  elapsed=11.365ms

INFO [08-10|09:43:15.856] New block                                index=10529 l1-timestamp=1623949464 l1-blocknumber=25541022 tx-hash=0x724d3272130a293fc5adcd8047b74d456a566f22f47fe576b985a97ab94ab892 queue-orign=sequencer gas=760728  fees=1.141092e-05  elapsed=21.296ms

INFO [08-10|09:43:15.871] New block                                index=10530 l1-timestamp=1623949464 l1-blocknumber=25541022 tx-hash=0x00cb6352b00f1aa78576a8b626b27b0ed4bdf567b72e5ffe328899e335939c8d queue-orign=sequencer gas=760728  fees=1.141092e-05  elapsed=9.115ms
`

And the l2geth's memory usage raised slowly till 64G, then my host crashed down by OOM

**Comment by optimisticben** [comment]
Thanks for the report, we are aware of the situation and working on it.

I opened an [issue](https://github.com/ethereum-optimism/optimism/issues/1333) to track under the optimism repo.
