### ISSUE TITLE
sync err 

### ISSUE THREAD

**Issue by wangtao19911111** [optimisticben/op-replica#48]
what this meanings and somet i can do？the after is op-replica_l2geth-replica_1`s error logs

Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: cannot fetch transaction 1022007: cannot fetch transaction: json: cannot unmarshal number -28 into Go struct field signature.transaction.decoded.sig.v of type uint？

**Comment by masayil** [comment]
pls update to the latest version. data-transport-layer-0.5.10 l2geth-0.5.4

**Comment by optimisticben** [comment]
pls update to the latest versions. 
data-transport-layer 0.5.10, l2geth 0.5.4.
