### ISSUE TITLE
sync error on testnet 

### ISSUE THREAD

**Issue by masayil** [optimisticben/op-replica#49]
data-transport-layer: 503 error
stop sync at block 13000
![image](https://user-images.githubusercontent.com/65291464/145751058-9d052a1e-6e1b-498d-9a65-780db48733c6.png)

**Comment by optimisticben** [comment]
503 can happen and should be temporary. Are you still having a problem? What `DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT` are you using?

**Comment by masayil** [comment]
yes.12 hours...

DATA_TRANSPORT_LAYER__ADDRESS_MANAGER=0x100Dd3b414Df5BbA2B542864fF94aF8024aFdf3a
DATA_TRANSPORT_LAYER__CONFIRMATIONS=12
DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS=true
DATA_TRANSPORT_LAYER__DB_PATH=/db
DATA_TRANSPORT_LAYER__DEFAULT_BACKEND=l2
DATA_TRANSPORT_LAYER__ETH_NETWORK_NAME=kovan
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=https://kovan.infura.io/v3/6d32f5cca3624ea6a0fc6c05a7816839
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://kovan.optimism.io
DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL=2000
DATA_TRANSPORT_LAYER__NODE_ENV=production
DATA_TRANSPORT_LAYER__POLLING_INTERVAL=500
DATA_TRANSPORT_LAYER__SENTRY_TRACE_RATE=0.05
DATA_TRANSPORT_LAYER__SERVER_HOSTNAME=0.0.0.0
DATA_TRANSPORT_LAYER__SERVER_PORT=7878
DATA_TRANSPORT_LAYER__SYNC_FROM_L1=false
DATA_TRANSPORT_LAYER__SYNC_FROM_L2=true
DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL=1000
DATA_TRANSPORT_LAYER__L2_CHAIN_ID=69
DATA_TRANSPORT_LAYER__L1_GAS_PRICE_BACKEND=l2
DEPLOYER_HTTP=
DATA_TRANSPORT_LAYER__ENABLE_METRICS=true
DATA_TRANSPORT_LAYER__L1_START_HEIGHT=27989623

**Comment by masayil** [comment]
![image](https://user-images.githubusercontent.com/65291464/145845162-adc6b85a-820c-4eca-b07f-7175217ce6be.png)
While synchronizing blocks in this interval ,the 503 error occurs

**Comment by optimisticben** [comment]
Confirmed, thanks for the report. Looking into it now.

**Comment by optimisticben** [comment]
Please check that the problem persists, it should be resolved.

(a new proxy setting limits json payload sizes, this lmit was > 5MB).

**Comment by masayil** [comment]
> 

I got the  same error in this interval - [48001-49001].This is very confusing
![image](https://user-images.githubusercontent.com/65291464/145927972-29b245a9-aa8c-4223-b9f9-cdb1bd913d77.png)

**Comment by optimisticben** [comment]
Seems I did not raise it enough. The max is much higher and we're monitoring now 👀
