### ISSUE TITLE
mainnet sync issuse

### ISSUE THREAD

**Issue by masayil** [optimisticben/op-replica#53]
1)![image](https://user-images.githubusercontent.com/65291464/147018027-07e7190d-7c8b-418b-a134-8676b2507966.png)
The node stop sync and output log - "Regenerated local transaction journal".
After I restart containers , sync will recover. However , about 30 mins later, it will stop sync again.

2)l2geth Param problem:
"ROLLUP_POLL_INTERVAL=1s" is wrong. It should be "ROLLUP_POLL_INTERVAL_FLAG=1s"

**Comment by optimisticben** [comment]
Thanks for the note on the `ROLLUP_POLL_INTERVAL_FLAG` flag.

Please update to the newest image tags and reopen if this is still an issue 🙏
