### ISSUE TITLE
[ Mainnet ] Container op-replica_data-transport-layer_1  sync error

### ISSUE THREAD

**Issue by jennie-bv** [optimisticben/op-replica#56]
`docker logs op-replica_data-transport-layer_1 --tail 20`

`{"level":50,"time":1641647734186,"extra":{"message":"TypeError: blocks is not iterable","stack":"TypeError: blocks is not iterable\n    at L2IngestionService._syncSequencerBlocks (/opt/optimism/packages/data-transport-layer/dist/src/services/l2-ingestion/service.js:148:29)\n    at async L2IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l2-ingestion/service.js:86:17)\n    at async L2IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service.js:33:9)\n    at async Promise.all (index 2)\n    at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:62:13)\n    at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service.js:33:9)\n    at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:69:9"},"msg":"Caught an unhandled error"}`

.ENV FILE

> DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=http://xxxxx:8999
DTL_IMAGE_TAG=0.5.10
ETH_NETWORK=mainnet
L2GETH_HTTP_PORT=9991
L2GETH_IMAGE_TAG=0.5.4
REPLICA_HEALTHCHECK__ETH_NETWORK_RPC_PROVIDER=http://xxxxx:8999
SHARED_ENV_PATH=./kustomize/replica/envs/mainnet

**Comment by yorickdowne** [comment]
You need a `DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT` pointing to an RPC server for the Ethereum L1. The L2 RPC endpoint would be the optimism sequencer URLs, e.g. `https://mainnet.optimism.ioi/`.

Successfully running over here. You may want to take a look at #55 for some small fixes such as restart, poll interval, etc; as well as traefik and haproxy shenanigans so tx can be sent while using a replica.

**Comment by jennie-bv** [comment]
> You need a `DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT` pointing to an RPC server for the Ethereum L1. The L2 RPC endpoint would be the optimism sequencer URLs, e.g. `https://mainnet.optimism.io/`.
> 
> Successfully running over here. You may want to take a look at #55 for some small fixes such as restart, poll interval, etc; as well as traefik and haproxy shenanigans so tx can be sent while using a replica.

**Comment by jennie-bv** [comment]
> You need a `DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT` pointing to an RPC server for the Ethereum L1. The L2 RPC endpoint would be the optimism sequencer URLs, e.g. `https://mainnet.optimism.io/`.
> 
> Successfully running over here. You may want to take a look at #55 for some small fixes such as restart, poll interval, etc; as well as traefik and haproxy shenanigans so tx can be sent while using a replica.

thx
