### ISSUE TITLE
ERR:Blocknumber monotonicity violation

### ISSUE THREAD

**Issue by masayil** [optimisticben/op-replica#61]
![image](https://user-images.githubusercontent.com/65291464/150084582-d48a447a-c1e7-47e8-9563-bd8c54250715.png)
I would like to know what causes this error. This error does not affect data synchronization.
Version:  1)ethereumoptimism/data-transport-layer   0.5.11  2) ethereumoptimism/l2geth                 0.5.6

**Comment by optimisticben** [comment]
Please open an issue under the optimism project. This repo is only for deployment purposes 🙏 

https://github.com/ethereum-optimism/optimism/issues
